export const states = [
  {id: 'ak', name: 'Alaska'},
  {id: 'al', name: 'Alabama'},
  {id: 'az', name: 'Arizona'},
  {id: 'ar', name: 'Arkansas'},
  {id: 'ca', name: 'California'},
  {id: 'co', name: 'Colorado'},
  {id: 'ct', name: 'Connecticut'},
  {id: 'de', name: 'Delaware'},
  {id: 'dc', name: 'Dist. of Columbia'},
  {id: 'fl', name: 'Florida'},
  {id: 'ga', name: 'Georgia'},
  {id: 'gu', name: 'Guam'},
  {id: 'hi', name: 'Hawaii'},
  {id: 'id', name: 'Idaho'},
  {id: 'il', name: 'Illinois'},
  {id: 'in', name: 'Indiana'},
  {id: 'ia', name: 'Iowa'},
  {id: 'ks', name: 'Kansas'},
  {id: 'ky', name: 'Kentucky'},
  {id: 'la', name: 'Louisiana'},
  {id: 'me', name: 'Maine'},
  {id: 'md', name: 'Maryland'},
  {id: 'mh', name: 'Marshall Islands'},
  {id: 'ma', name: 'Massachusetts'},
  {id: 'mi', name: 'Michigan'},
  {id: 'mn', name: 'Minnesota'},
  {id: 'ms', name: 'Mississippi'},
  {id: 'mo', name: 'Missouri'},
  {id: 'mt', name: 'Montana'},
  {id: 'ne', name: 'Nebraska'},
  {id: 'nv', name: 'Nevada'},
  {id: 'nh', name: 'New Hampshire'},
  {id: 'nm', name: 'New Mexico'},
  {id: 'ny', name: 'New York'},
  {id: 'nj', name: 'New Jersey'},
  {id: 'nc', name: 'North Carolina'},
  {id: 'nd', name: 'North Dakota'},
  {id: 'oh', name: 'Ohio'},
  {id: 'ok', name: 'Oklahoma'},
  {id: 'or', name: 'Oregon'},
  {id: 'pa', name: 'Pennsylvania'},
  {id: 'pr', name: 'Puerto Rico'},
  {id: 'ri', name: 'Rhode Island'},
  {id: 'sc', name: 'South Carolina'},
  {id: 'sd', name: 'South Dakota'},
  {id: 'tn', name: 'Tennessee'},
  {id: 'te', name: 'Territories'},
  {id: 'tx', name: 'Texas', percent: '100'},
  {id: 'ut', name: 'Utah'},
  {id: 've', name: 'Vermont'},
  {id: 'va', name: 'Virginia'},
  {id: 'vi', name: 'Virgin Islands'},
  {id: 'vt', name: 'Vermont'},
  {id: 'wa', name: 'Washington'},
  {id: 'wv', name: 'West Virginia'},
  {id: 'wi', name: 'Wisconsin'},
  {id: 'wy', name: 'Wyoming'}
]
